"""Generate per-rule docs/rules/<rule_id>.md pages from RuleDefinition metadata."""

from __future__ import annotations

import difflib
from pathlib import Path

from hasscheck.rules.base import RuleDefinition
from hasscheck.rules.registry import RULES_BY_ID

_AUTOGEN_MARKER = "<!-- HANDWRITTEN BELOW THIS LINE -->"


def render_page(rule: RuleDefinition) -> str:
    """Render the auto-generated portion of a rule page.

    Returns a string ending with the _AUTOGEN_MARKER line.
    Everything after the marker is user-owned and never touched by the renderer.
    """
    overridable_str = str(rule.overridable)

    lines: list[str] = [
        f"# {rule.id}",
        "",
        "> **Generated from `RuleDefinition` metadata.** Edit only the section below the",
        '> "HANDWRITTEN BELOW" marker; everything above is regenerated by',
        "> `hasscheck docs-render`.",
        "",
        "## Summary",
        "",
        rule.title,
        "",
        "## Why",
        "",
        rule.why,
        "",
        "## Status behavior",
        "",
        "| Field | Value |",
        "|---|---|",
        f"| Category | {rule.category} |",
        f"| Severity | {rule.severity.value} |",
        f"| Overridable | {overridable_str} |",
        f"| Version | {rule.version} |",
        "",
        "## Source",
        "",
        f"- {rule.source_url}",
        f"- `source_checked_at`: {rule.source.checked_at}",
        "",
    ]

    # --- Optional metadata sections (rendered only when non-default) ---
    # Order: Tags, Confidence, Deprecated, Replacement
    # Spec §4 + Design §5: profiles, advisory_id, related_quality_scale_rule deferred.

    if rule.tags:
        tag_list = ", ".join(f"`{t}`" for t in rule.tags)
        lines += [
            "## Tags",
            "",
            tag_list,
            "",
        ]

    if rule.confidence != "high":
        lines += [
            "## Confidence",
            "",
            rule.confidence,
            "",
        ]

    if rule.deprecated:
        deprecation_lines = [
            "## Deprecated",
            "",
            "> This rule is deprecated.",
        ]
        if rule.deprecated_in_version:
            deprecation_lines += [
                ">",
                f"> Deprecated in version: {rule.deprecated_in_version}",
            ]
        deprecation_lines.append("")
        lines += deprecation_lines

    if rule.replacement_rule is not None:
        lines += [
            "## Replacement",
            "",
            f"See [{rule.replacement_rule}](./{rule.replacement_rule}.md).",
            "",
        ]

    lines.append(_AUTOGEN_MARKER)

    return "\n".join(lines)


def write_page(rule: RuleDefinition, docs_dir: Path) -> tuple[Path, bool]:
    """Write or update a rule's docs page.

    The auto-generated section (everything up to and including the marker) is
    always regenerated. Any content AFTER the marker is preserved verbatim.

    Returns (path, was_changed) where was_changed is True if the file was
    created or its auto-section differed from what was already on disk.
    """
    docs_dir.mkdir(parents=True, exist_ok=True)
    page = docs_dir / f"{rule.id}.md"

    new_auto = render_page(rule)

    preserved_tail = ""
    if page.is_file():
        existing = page.read_text(encoding="utf-8")
        marker_idx = existing.find(_AUTOGEN_MARKER)
        if marker_idx != -1:
            # Keep everything after the marker line (including trailing newline)
            after_marker = existing[marker_idx + len(_AUTOGEN_MARKER) :]
            preserved_tail = after_marker

    new_content = new_auto + preserved_tail
    # Ensure file ends with a newline (required by pre-commit end-of-file-fixer)
    if not new_content.endswith("\n"):
        new_content += "\n"

    if page.is_file():
        existing_content = page.read_text(encoding="utf-8")
        if existing_content == new_content:
            return page, False

    page.write_text(new_content, encoding="utf-8")
    return page, True


def render_all(docs_dir: Path) -> dict[str, bool]:
    """Render every registered rule page.

    Returns a mapping of {rule_id: was_changed}.
    """
    results: dict[str, bool] = {}
    for rule_id, rule in RULES_BY_ID.items():
        _, was_changed = write_page(rule, docs_dir)
        results[rule_id] = was_changed
    return results


def check_drift(docs_dir: Path) -> dict[str, str]:
    """Check whether any rule page's auto-section is out of date.

    Returns {rule_id: diff_string} for rules whose page is missing or stale.
    An empty dict means everything is up to date.
    """
    drift: dict[str, str] = {}
    for rule_id, rule in RULES_BY_ID.items():
        page = docs_dir / f"{rule_id}.md"

        if not page.is_file():
            drift[rule_id] = f"Missing page: {page}"
            continue

        existing = page.read_text(encoding="utf-8")
        # Extract only the auto section (up to and including marker)
        marker_idx = existing.find(_AUTOGEN_MARKER)
        if marker_idx == -1:
            # No marker found — whole file is considered stale
            existing_auto = existing
        else:
            existing_auto = existing[: marker_idx + len(_AUTOGEN_MARKER)]

        expected_auto = render_page(rule)

        if existing_auto != expected_auto:
            diff = "".join(
                difflib.unified_diff(
                    existing_auto.splitlines(keepends=True),
                    expected_auto.splitlines(keepends=True),
                    fromfile=f"{rule_id}.md (current)",
                    tofile=f"{rule_id}.md (expected)",
                )
            )
            drift[rule_id] = diff

    return drift
