# Generated by hasscheck — review before committing.
# Docs: https://developers.home-assistant.io/docs/core/integration/diagnostics/
from __future__ import annotations

from typing import Any

from homeassistant.config_entries import ConfigEntry
from homeassistant.core import HomeAssistant

# Add any keys that should be redacted from diagnostics output.
# Common sensitive fields: API keys, tokens, passwords, location data.
TO_REDACT: list[str] = [
    "api_key",
    "password",
    "token",
    "latitude",
    "longitude",
]


async def async_get_config_entry_diagnostics(
    hass: HomeAssistant,
    entry: ConfigEntry,
) -> dict[str, Any]:
    """Return diagnostics for a config entry."""
    return {
        "entry": redact_data(dict(entry.data), TO_REDACT),
        "options": redact_data(dict(entry.options), TO_REDACT),
    }


def redact_data(data: dict[str, Any], to_redact: list[str]) -> dict[str, Any]:
    """Redact sensitive data from a dict."""
    redacted = dict(data)
    for key in to_redact:
        if key in redacted:
            redacted[key] = "**REDACTED**"
    return redacted
